### ISSUE TITLE
Not compatible with NW.js atm

### ISSUE THREAD

**Issue by RSATom** [RSATom/wcjs-gs#1]
```
JsPlayer.cpp:305:9: error: ‘MaybeLocal’ is not a member of ‘v8’
```

Please upvote if you need fix it.
##

**Comment by RSATom** [comment]
it's very possible it's not issue with latest NW.js versions anymore.

**Comment by RSATom** [comment]
It works with latest NW.js if use hack: https://github.com/RSATom/wcjs-gs/issues/8#issuecomment-625877375

**Comment by anesuc** [comment]
Commenting so that I can get notified if any progress happens on this
