### ISSUE TITLE
Port to Windows

### ISSUE THREAD

**Issue by RSATom** [RSATom/wcjs-gs#4]
subj
##

**Comment by colek42** [comment]
what is the scope of work for this?

**Comment by RSATom** [comment]
Not too much. https://github.com/RSATom/wcjs-gs/blob/master/CMakeLists.txt should be modified to be able find gstreamer libraries.  Now it uses `pkg-config` but it's not available on Windows.

**Comment by colek42** [comment]
good news, we need PTS for our app.  I think we will give this a shot next week.  Are there any other limitations that we should consider?

**Comment by RSATom** [comment]
Limitations are the same as described there: https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues)

Another issue - limited available JS API, but it solvable without too much effort.

**Comment by zoolyka** [comment]
Hello, is there any chance to have the Windows build working? Or to have it precompiled? This project would add super great features to electron apps. Thank you.

**Comment by RSATom** [comment]
At the moment I don't have any plans to do any contribution to this project since there are no much interest to this project from community. Sorry.
