### ISSUE TITLE
Integration guide

### ISSUE THREAD

**Issue by cchersin** [RSATom/wcjs-gs#5]
wcjs-gs is a very interesting project, but it lacks of an installation/integration guide. 

How can I integrate it in my nw.js project? GStreamer needs to be installed separately?  Which gstreamer version is compatible with wcjs-gs?

Thanks

**Comment by RSATom** [comment]
tbh, it's just proof-of-consept atm. It supports only Linux and GStreamer 1.x.

**Comment by superlou** [comment]
I'm interested in using this on Linux with GStreamer 1.x and Electron.  I currently have some shmsinks that I'd like to render into an Electron app.  Is this an appropriate use case of this library?

**Comment by RSATom** [comment]
@superlou, The purposes of this library is:
a) ability interact with gstreamer pipeline from JavaScript
б) pass memory blocks from appsink to JavaScript

and it's pretty possible do:
c) get memory blocks from JavaScript and pass it to gstreamer pipeline (via appsrc for example)

**Comment by superlou** [comment]
@RSATom, thanks.  Is there an example somewhere on how to use this?  The [demo project](github.com/RSATom/wcjs-ugly-demo/blob/wcjs-gs) gives a 404.

**Comment by RSATom** [comment]
Yes, please look https://github.com/RSATom/wcjs-ugly-demo/tree/wcjs-gs

**Comment by superlou** [comment]
That's a big help, thanks.  Is there significant overhead with playing videos this way on a canvas as opposed to the processing required to draw an ximagesink onto a window handle/XID?  I'm looking at an application where I'll need to play around a dozen video streams at once.

**Comment by RSATom** [comment]
Yes, it has overhead. Please read this: https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues) about reasons (it's about `WebChimera.js`, but with `wcjs-gs` it's all the same)

If you need best possible performance, you have to avoid any html engines.

**Comment by superlou** [comment]
Thanks for the link.  I'm going to try and get it working to benchmark it in my application, but I think you're right that I may need to avoid the overhead.
