### ISSUE TITLE
Node version problem while compiling web chimera

### ISSUE THREAD

**Issue by cdeveloperonunix** [RSATom/wcjs-gs#6]
i am having ubuntu 12 04 armhf architecture device, where installed with node version of 0.6.12 is installed.

When i run build_node.sh, it throws the following error:

npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/cmake-js/1.1.1

npm ERR! Error: failed to fetch from registry: cmake-js/1.1.1
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:209:10)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at CleartextStream.<anonymous> (http.js:1137:11)
npm ERR!     at CleartextStream.emit (events.js:67:17)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/ubuntu/Downloads/wcjs-gs-master/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.1.10-alna
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/ubuntu/Downloads/wcjs-gs-master
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: cmake-js/1.1.1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/Downloads/wcjs-gs-master/npm-debug.log
npm not o

**Comment by RSATom** [comment]
I'm afraid node.js v0.6.12 is just too old. I've never tried wcjs with such old version.
